n=[10,14,3,26,44,36,23,23,14]
# print(len(n))
# print(min(n))
# print(max(n))
# print(sum(n))
# print("end")
# n.append(77)
# print(n)
# n.insert(7,88)
# print(n)
m=[22,82,100]
# n.append(m)
# print(n)
# n.extend(m)
# print(n)
# m.clear()
# print(m)
# n.sort()
# print(n)
# v=n.count(144)
# print(v)
# l=m.pop()
# print(l)
# print(m)
# m.remove(2)
# print(m)
print(n.index(3))
